version: "3"
services:
  ubuntu22.04-dev:
    image: ubuntu:22.04
    container_name: ubuntu22.04-dev
    environment:
      TZ: ${TZ}
      MIRROR: ${MIRROR}
      PHP_EXTRA_EXTENSIONS: ${PHP_EXTRA_EXTENSIONS}
      ZZ_TOOLS: /usr/local/zz-tools
    volumes:
      - ./tools:/usr/local/zz-tools
      - ./:/srv/docker-runtime
    command: [ "bash", "-c", "chmod +x /usr/local/zz-tools/*; tail -f  /dev/stdout"]
  alpine3.16-dev:
    image: alpine:3.16
    container_name:   alpine3.16-dev
    environment:
      TZ: ${TZ}
      MIRROR: ${MIRROR}
      PHP_EXTRA_EXTENSIONS: ${PHP_EXTRA_EXTENSIONS}
      ZZ_TOOLS: /usr/local/zz-tools
    volumes:
      - ./tools:/usr/local/zz-tools
      - ./:/srv/docker-runtime
    command: [ "sh", "-c", "chmod +x /usr/local/zz-tools/*; tail -f  /dev/stdout" ]
