version: "3.1"
services:
  # php7.4
  php74-nginx-ubuntu:
    image: zdzserver/runtime:php7.4-nginx-ubuntu
    container_name: php74-nginx-ubuntu
    volumes:
      # 你的项目目录，可以目录下多个项目，需要自定义nginx配置文件
      - $PHP7_WEB_ROOT:/var/www
      - $PHP7_NGINX_CONF_D:/etc/nginx/conf.d
    networks:
      php:
    # 映射nginx监听的端口, 多个映射多个端口，内部端口不冲突就行
    ports:
      - "8080:80"
  # php8.1
  php81-nginx-ubuntu:
    image: zdzserver/runtime:php8.1-nginx-ubuntu
    container_name: php81-nginx-ubuntu
    networks:
      php:
    volumes:
      # 你的项目目录，可以目录下多个项目，需要自定义nginx配置文件
      - $PHP8_WEB_ROOT:/var/www
      - $PHP8_NGINX_CONF_D:/etc/nginx/conf.d
    # 映射nginx监听的端口, 多个映射多个端口，内部端口不冲突就行
    ports:
      - "8081:80"

  mysql:
    image: mysql:5.7
    container_name: mysql57
    restart: always
    environment:
      TZ: "Asia/Shanghai" # 修改时区
      MYSQL_ROOT_PASSWORD: example  # root 密码
    ports:
      - "3306:3306"
    volumes:
      - $MYSQL57_DATA:/var/lib/mysql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci
      - --log_timestamps=SYSTEM
      - --lower_case_table_names=1
    networks:
      php:

  redis:
    image: redis:6.2.7
    container_name: redis62
    restart: always
    environment:
      TZ: Asia/Shanghai
    volumes:
      - $REDIS6_DATA:/data
      - $REDIS6_CONFIG:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    command:
      - redis-server
      - /usr/local/etc/redis/redis.conf
    networks:
      php:

networks:
  php: