version: '3.1'
services:
  db:
    image: mysql:8.0.30
    restart: always
#    network_mode: "host"
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql/db:/var/lib/mysql
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ROOT_PASSWORD: example
    command:
    - --character-set-server=utf8mb4
    - --collation-server=utf8mb4_general_ci
    - --log_timestamps=SYSTEM
    - --lower_case_table_names=1
    networks:
      mysql:
  adminer:
    image: adminer
    restart: always
    ports:
      - "30080:8080"
    networks:
      mysql:
networks:
  mysql: